// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var company = {
  name: "Zasta Enterprises Private Limited",
  brand: "Zasta Group",
  tagline: "Based in Hyderabad, delivering infrastructure excellence.",
  headquarters: "Hyderabad, Telangana, India",
  website: "https://zastagroup.com",
  contactEmail: "hr@zastagroup.com",
  sectors: [
    "Construction & Infrastructure",
    "Engineering Consultancy",
    "Workforce Solutions",
    "Digital Construction Technology"
  ],
  products: [
    {
      name: "Construction Quality Management Platform",
      description: "Digital platform for construction quality, safety, and compliance management."
    },
    {
      name: "NirmanJobs",
      url: "https://nirmanjobs.com",
      description: "Job platform for construction, engineering, and infrastructure professionals."
    }
  ],
  stats: {
    expertEngineers: "170+",
    projectsCompleted: "40+"
  }
};
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company information",
  description: "Get an overview of Zasta Group \u2014 headquarters, sectors served, products, and key stats.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(company, null, 2) }],
    structuredContent: { company }
  })
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var services = [
  {
    id: "construction-quality-management",
    name: "Construction Quality Management Platform",
    summary: "End-to-end digital platform for managing quality, safety, and compliance across construction projects \u2014 enabling site inspections, checklists, defect tracking, and real-time reporting.",
    highlights: [
      "Digital site inspections and QA/QC checklists",
      "Defect and snag management with photo evidence",
      "Real-time dashboards for project managers and consultants",
      "Compliance and audit trail reporting"
    ]
  },
  {
    id: "nirmanjobs",
    name: "NirmanJobs",
    url: "https://nirmanjobs.com",
    summary: "Dedicated job platform connecting skilled construction, engineering, and infrastructure professionals with employers across India.",
    highlights: [
      "Job listings for civil, MEP, QA/QC, design, and project management roles",
      "Employer branding and CV database access",
      "Focused on the construction and infrastructure industry"
    ]
  },
  {
    id: "workforce-solutions",
    name: "Workforce & Manpower Solutions",
    summary: "Providing expert engineers, technicians, and support staff for infrastructure and construction projects across India and abroad."
  },
  {
    id: "construction-management",
    name: "Construction & Project Management",
    summary: "Turnkey construction management, project monitoring, and consultancy for residential, commercial, and industrial developments."
  }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List Zasta Group services",
  description: "List the services and products offered by Zasta Group, including the Construction Quality Management Platform and NirmanJobs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-job-openings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var openings = [
  {
    id: 1,
    title: "MEP Engineer",
    department: "Mechanical Engineering",
    location: "Chevella, Hyderabad, India",
    type: "Full-time",
    experience: "5+ years",
    vacancy: 1,
    postedDate: "2026-01-02",
    description: "Oversee on-site installation and coordination of Mechanical, Electrical, and Plumbing services for residential projects."
  },
  {
    id: 2,
    title: "Design Coordinator",
    department: "Civil Engineering",
    location: "Chevella, Hyderabad, India",
    type: "Full-time",
    experience: "8+ years",
    vacancy: 1,
    postedDate: "2026-01-02",
    description: "Bridge between design consultants and the construction team; streamline information flow and resolve design conflicts."
  },
  {
    id: 3,
    title: "Quality Manager",
    department: "Quality Assurance & Control",
    location: "Chevella, Hyderabad, India",
    type: "Full-time",
    experience: "10+ years",
    vacancy: 1,
    postedDate: "2026-01-02",
    description: "Lead the QA/QC department; develop and maintain quality management systems across residential projects."
  },
  {
    id: 4,
    title: "Quality Manager",
    department: "Quality Assurance & Control",
    location: "Tarnaka, Hyderabad, India",
    type: "Full-time",
    experience: "10+ years",
    vacancy: 1,
    postedDate: "2026-01-02",
    description: "Oversee QA/QC functions for high-end residential projects; establish quality benchmarks and site inspections."
  }
];
var list_job_openings_default = defineTool3({
  name: "list_job_openings",
  title: "List current job openings",
  description: "List current job openings at Zasta Group, optionally filtered by location or department (case-insensitive substring match).",
  inputSchema: {
    location: z.string().optional().describe("Optional location filter, e.g. 'Hyderabad'."),
    department: z.string().optional().describe("Optional department filter, e.g. 'Quality'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ location, department }) => {
    const loc = location?.toLowerCase();
    const dep = department?.toLowerCase();
    const filtered = openings.filter(
      (o) => (!loc || o.location.toLowerCase().includes(loc)) && (!dep || o.department.toLowerCase().includes(dep))
    );
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { openings: filtered, count: filtered.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "zasta-group-mcp",
  title: "Zasta Group MCP",
  version: "0.1.0",
  instructions: "Public tools about Zasta Group \u2014 company info, services (including the Construction Quality Management Platform and NirmanJobs), and current job openings.",
  tools: [get_company_info_default, list_services_default, list_job_openings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
